chore: re-run cicd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,5 +49,5 @@ jobs:
               pm2 reload $APP_NAME || { echo "Error: Failed to reload PM2 app $APP_NAME"; exit 1; }
             else
               echo "PM2 app $APP_NAME not found. Starting pm2."
-              pm2 start npm --name vercel-be --run start:all || { echo "Error: Failed to start PM2 app $APP_NAME"; exit 1; }
+              pm2 start npm --name vercel-be -- run start:all || { echo "Error: Failed to start PM2 app $APP_NAME"; exit 1; }
             fi
